name: CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest
          if [ -f device/requirements.txt ]; then pip install -r device/requirements.txt; fi
      - name: Run tests
        run: pytest
        working-directory: device

  functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: functions
      - name: Run tests
        run: npm test
        working-directory: functions

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Android placeholder
        run: echo "Android build not yet configured"
        working-directory: mobile-android
